
language: groovy

sudo: false

before_script:
 - ./gradlew -S clean --console=plain

install: true

script:
 - ./gradlew -S -i --console=plain assemble
 - ./gradlew -S -i --console=plain test
 - ./gradlew -S -i --console=plain gradleTest -DgradleTest.versions=2.8,2.9
 - ./gradlew -S -i --console=plain gradleTest -DgradleTest.versions=2.10,2.12,2.14.1
 - ./gradlew -S -i --console=plain gradleTest -DgradleTest.versions=3.0,3.1,3.2.1
 - ./gradlew -S -i --console=plain gradleTest -DgradleTest.versions=3.3,3.4,3.5
 - ./gradlew -S -i --console=plain gradleTest -DgradleTest.versions=4.0

jdk:
 - oraclejdk8
# - oraclejdk7
# - openjdk7
# - openjdk6

os:
 - linux
# osx_image: xcode7.3

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
#after_success: ./gradlew coveralls -PbintrayUser= -PbintrayApiKey

branches:
  only:
    - master
    - development
#    - release