version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat test --info --no-daemon
  - gradlew.bat gradleTest --info --no-daemon -DgradleTest.versions=2.8,2.9
  - gradlew.bat gradleTest --info --no-daemon -DgradleTest.versions=2.10,2.11,2.12,2.13,2.14.1
  - gradlew.bat gradleTest --info --no-daemon -DgradleTest.versions=3.0,3.1,3.2.1,3.3,3.4,3.5
  - gradlew.bat gradleTest --info --no-daemon -DgradleTest.versions=4.0

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true

